Se extraen los datos históricos de las 10 monedas relacionadas con Inteligencia Artificial ranquedas por Market Cap en CoinGecko

# Top Artificial Intelligence (AI) Coins by Market Cap

Antes de empezar con la extracción de los datos se necesita conocer el nombre de las monedas por lo que se baja un archivo json que contiene el listado de todas las monedas que existen con su respectivo id,símbolo y nombre.

In [1]:
import pandas as pd
import json
#Haciendo una consulta desde la web se descarga el archivo json para concocer el listado de las monedas y su respectivo id, símbolo.
with open('monedas_ids.json', 'r',encoding='utf-8') as f:
    data = json.load(f)

# Convertir a DataFrame
df = pd.DataFrame(data)

In [2]:
df

,id,symbol,name,platforms
0,01coin,zoc,01coin,{}
1,0chain,zcn,Zus,{'ethereum': '0xb9ef770b6a5e12e45983c5d8054525...
2,0vix-protocol,vix,0VIX Protocol,{}
3,0x,zrx,0x Protocol,{'ethereum': '0xe41d2489571d322189246dafa5ebde...
4,0x0-ai-ai-smart-contract,0x0,0x0.ai: AI Smart Contract,{'ethereum': '0x5a3e6a77ba2f983ec0d371ea3b475f...
...,...,...,...,...
10057,zynecoin,zyn,Zynecoin,{}
10058,zynergy,zyn,Zynergy,{'zksync': '0x0231b3de40b6b3bdd28dcef037f1b7a3...
10059,zyrri,zyr,Zyrri,{}
10060,zyx,zyx,ZYX,{'ethereum': '0xf974b5f9ac9c6632fee8b76c61b024...
10061,zzz,zzz,GoSleep ZZZ,{'arbitrum-one': '0x7a2c1b8e26c48a5b73816b7ec8...

In [2]:
# Se buscan las 10 monedas que tienen que ver con tecnología, esto para saber los ids y poderlos usarlos en la extracción de los datos 
lista=['Render','SingularityNET','Fetch.ai',
'Akash Network','Ocean Protocol', 'iExec RLC','OriginTrail',
'inSure DeFi','IQ','Numeraire']

selected_rows = df[df['name'].isin(lista)]
lista_id_criptos= selected_rows['id'].values
lista_id_criptos

array(['akash-network', 'everipedia', 'fetch-ai', 'iexec-rlc', 'insure',
       'numeraire', 'ocean-protocol', 'origintrail', 'render-token',
       'singularitynet'], dtype=object)

# Extracción de datos con Requests

In [11]:
import requests
import pandas as pd
import matplotlib.pyplot as plt

# Configurar la URL base de la API de CoinGecko
base_url = "https://api.coingecko.com/api/v3"

In [12]:
# Lista de monedas seleccionadas
coins = ['akash-network', 'everipedia', 'fetch-ai', 'iexec-rlc', 'insure', 'numeraire', 'ocean-protocol', 'origintrail', 'render-token', 'singularitynet']

# Parámetros para la solicitud
params = {
    "vs_currency": "usd",      # Moneda de comparación (USD en este caso)
    "days": "1825"             # Datos históricos de los últimos 5 años (aproximadamente)
}

# Crear un DataFrame para almacenar los datos históricos
historical_data = pd.DataFrame()

# Iterar sobre las monedas y obtener los datos históricos
for coin in coins:
    response = requests.get(f"{base_url}/coins/{coin}/market_chart", params=params)
    data = response.json()
    
    # Crear un DataFrame para los datos de cada moneda
    df = pd.DataFrame(data["prices"], columns=["timestamp", coin])
    df["timestamp"] = pd.to_datetime(df["timestamp"], unit="ms")
    df.set_index("timestamp", inplace=True)
    
    # Agregar los datos al DataFrame principal
    historical_data = pd.concat([historical_data, df], axis=1)

# Mostrar los primeros registros del DataFrame
historical_data

,akash-network,everipedia,fetch-ai,iexec-rlc,insure,numeraire,ocean-protocol,origintrail,render-token,singularitynet
timestamp,,,,,,,,,,
2018-08-18 00:00:00,NaN,0.015792,NaN,0.352144,NaN,7.064057,NaN,0.049958,NaN,0.051190
2018-08-19 00:00:00,NaN,0.014093,NaN,0.328280,NaN,6.156209,NaN,0.046672,NaN,0.044826
2018-08-20 00:00:00,NaN,0.015060,NaN,0.348550,NaN,6.504095,NaN,0.049395,NaN,0.047223
2018-08-21 00:00:00,NaN,0.013841,NaN,0.321180,NaN,6.087304,NaN,0.047193,NaN,0.042227
2018-08-22 00:00:00,NaN,0.013685,NaN,0.340655,NaN,5.985059,NaN,0.046938,NaN,0.042497
...,...,...,...,...,...,...,...,...,...,...
2023-08-16 22:56:32,NaN,NaN,0.195233,NaN,NaN,11.888841,NaN,NaN,NaN,NaN
2023-08-16 22:56:35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.233709,NaN,NaN
2023-08-16 22:56:36,NaN,NaN,NaN,NaN,0.00318,NaN,NaN,NaN,NaN,NaN
2023-08-16 22:56:37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.563358,NaN
2023-08-16 22:56:40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.191899

# Extracción de datos HISTÓRICOS con la librería CoinGeckoApi

['akash-network', 'everipedia', 'fetch-ai', 'iexec-rlc', 'insure','numeraire', 'ocean-protocol', 'origintrail', 'render-token','singularitynet']

In [21]:
from pycoingecko import CoinGeckoAPI
import pandas as pd
import time 
cg=CoinGeckoAPI()

In [9]:
# Convertir las fechas a formato Unix Timestamp
from_date = '01-01-2018'
to_date = '16-08-2023'
inicio = int(time.mktime(time.strptime(from_date, '%d-%m-%Y')))
final= int(time.mktime(time.strptime(to_date, '%d-%m-%Y')))

coin_history=cg.get_coin_market_chart_range_by_id(id='akash-network',
vs_currency='usd',from_timestamp=inicio,to_timestamp=final,localization=False)
coin_history_df=pd.DataFrame(coin_history)
coin_history_df

,prices,market_caps,total_volumes
0,"[1602806400000, 0.4020129704686936]","[1602806400000, 0.0]","[1602806400000, 1498615.9110537868]"
1,"[1602892800000, 0.4020129704686936]","[1602892800000, 0.0]","[1602892800000, 1498615.9110537868]"
2,"[1602979200000, 0.4472221643081897]","[1602979200000, 0.0]","[1602979200000, 660810.997760138]"
3,"[1603065600000, 0.5132367676427917]","[1603065600000, 3037564.3669883427]","[1603065600000, 769329.5970141214]"
4,"[1603152000000, 0.409010786511229]","[1603152000000, 2430235.0703865457]","[1603152000000, 597323.4427288639]"
...,...,...,...
1029,"[1691798400000, 1.1682307690639024]","[1691798400000, 255310914.53545454]","[1691798400000, 6501372.671378335]"
1030,"[1691884800000, 1.3167030358780163]","[1691884800000, 284091554.4639579]","[1691884800000, 8592521.756026585]"
1031,"[1691971200000, 1.1958511174233528]","[1691971200000, 258209392.12977675]","[1691971200000, 4957074.508435666]"
1032,"[1692057600000, 1.1803409080230722]","[1692057600000, 255930744.13776404]","[1692057600000, 4193125.0143395723]"
1033,"[1692144000000, 1.1548542096129428]","[1692144000000, 250403491.83692214]","[1692144000000, 2517305.951678036]"

akash-network

In [33]:
# Convertir las fechas a formato Unix Timestamp
from_date = '01-01-2018'
to_date = '16-08-2023'

from_timestamp = int(time.mktime(time.strptime(from_date, '%d-%m-%Y')))
to_timestamp = int(time.mktime(time.strptime(to_date, '%d-%m-%Y')))

coin_history = cg.get_coin_market_chart_range_by_id(id='akash-network',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df = pd.DataFrame(coin_history['prices'], columns=['Timestamp', 'Price'])
coin_history_df['Timestamp'] = pd.to_datetime(coin_history_df['Timestamp'], unit='ms')

coin_history_df['date'] = coin_history_df['Timestamp'].dt.date
coin_history_df['market_caps'] = [entry[1] for entry in coin_history['market_caps']]
coin_history_df['total_volumes'] = [entry[1] for entry in coin_history['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df = coin_history_df[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df.columns = ['fecha', 'price_akash', 'market_akash', 'vol_akash']
akash_network_df= coin_history_df
akash_network_df

           fecha  price_akash  market_akash     vol_akash
0     2020-10-16     0.402013  0.000000e+00  1.498616e+06
1     2020-10-17     0.402013  0.000000e+00  1.498616e+06
2     2020-10-18     0.447222  0.000000e+00  6.608110e+05
3     2020-10-19     0.513237  3.037564e+06  7.693296e+05
4     2020-10-20     0.409011  2.430235e+06  5.973234e+05
...          ...          ...           ...           ...
1029  2023-08-12     1.168231  2.553109e+08  6.501373e+06
1030  2023-08-13     1.316703  2.840916e+08  8.592522e+06
1031  2023-08-14     1.195851  2.582094e+08  4.957075e+06
1032  2023-08-15     1.180341  2.559307e+08  4.193125e+06
1033  2023-08-16     1.154854  2.504035e+08  2.517306e+06

[1034 rows x 4 columns]

everipedia

In [32]:
# Convertir las fechas a formato Unix Timestamp
from_date = '01-01-2018'
to_date = '16-08-2023'

from_timestamp = int(time.mktime(time.strptime(from_date, '%d-%m-%Y')))
to_timestamp = int(time.mktime(time.strptime(to_date, '%d-%m-%Y')))

coin_history2 = cg.get_coin_market_chart_range_by_id(id='everipedia',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df2 = pd.DataFrame(coin_history2['prices'], columns=['Timestamp', 'Price'])
coin_history_df2['Timestamp'] = pd.to_datetime(coin_history_df2['Timestamp'], unit='ms')

coin_history_df2['date'] = coin_history_df2['Timestamp'].dt.date
coin_history_df2['market_caps'] = [entry[1] for entry in coin_history2['market_caps']]
coin_history_df2['total_volumes'] = [entry[1] for entry in coin_history2['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df2 = coin_history_df2[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df2.columns = ['fecha', 'price_everipedia', 'market_everipedia', 'vol_everipedia']
everipedia_df= coin_history_df2
everipedia_df

           fecha  price_everipedia  market_everipedia  vol_everipedia
0     2018-07-17          0.055321       0.000000e+00    1.820751e+06
1     2018-07-18          0.056920       0.000000e+00    2.442063e+06
2     2018-07-19          0.049822       0.000000e+00    9.350607e+05
3     2018-07-20          0.043515       0.000000e+00    5.516436e+05
4     2018-07-21          0.031520       0.000000e+00    4.056037e+05
...          ...               ...                ...             ...
1852  2023-08-12          0.005377       8.745598e+07    3.208282e+06
1853  2023-08-13          0.005319       8.720517e+07    1.787888e+06
1854  2023-08-14          0.005266       8.634871e+07    1.820463e+06
1855  2023-08-15          0.005202       8.541092e+07    3.784513e+06
1856  2023-08-16          0.004988       8.166038e+07    3.016921e+06

[1857 rows x 4 columns]

fetch_ai

In [31]:
coin_history3 = cg.get_coin_market_chart_range_by_id(id='fetch-ai',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df3 = pd.DataFrame(coin_history3['prices'], columns=['Timestamp', 'Price'])
coin_history_df3['Timestamp'] = pd.to_datetime(coin_history_df3['Timestamp'], unit='ms')

coin_history_df3['date'] = coin_history_df3['Timestamp'].dt.date
coin_history_df3['market_caps'] = [entry[1] for entry in coin_history3['market_caps']]
coin_history_df3['total_volumes'] = [entry[1] for entry in coin_history3['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df3 = coin_history_df3[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df3.columns = ['fecha', 'price_fetch_ai', 'market_fetch_ai', 'vol_fetch_ai']
fetch_ai_df= coin_history_df3
fetch_ai_df

           fecha  price_fetch_ai  market_fetch_ai  vol_fetch_ai
0     2019-03-01        0.354598     0.000000e+00  1.407394e+08
1     2019-03-02        0.439896     0.000000e+00  1.190594e+08
2     2019-03-03        0.400913     0.000000e+00  4.235870e+07
3     2019-03-04        0.357126     0.000000e+00  3.275992e+07
4     2019-03-05        0.330658     0.000000e+00  3.734551e+07
...          ...             ...              ...           ...
1625  2023-08-12        0.202119     2.108971e+08  1.137004e+07
1626  2023-08-13        0.200333     2.090437e+08  1.132715e+07
1627  2023-08-14        0.219619     2.291141e+08  4.594561e+07
1628  2023-08-15        0.220334     2.300798e+08  1.052221e+08
1629  2023-08-16        0.203116     2.118678e+08  3.675603e+07

[1630 rows x 4 columns]

iexec-rlc

In [30]:
coin_history4 = cg.get_coin_market_chart_range_by_id(id='iexec-rlc',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df4 = pd.DataFrame(coin_history4['prices'], columns=['Timestamp', 'Price'])
coin_history_df4['Timestamp'] = pd.to_datetime(coin_history_df4['Timestamp'], unit='ms')

coin_history_df4['date'] = coin_history_df4['Timestamp'].dt.date
coin_history_df4['market_caps'] = [entry[1] for entry in coin_history4['market_caps']]
coin_history_df4['total_volumes'] = [entry[1] for entry in coin_history4['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df4 = coin_history_df4[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df4.columns = ['fecha', 'price_iexec_rlc', 'market_iexec_rlc', 'vol_iexec_rlc']
iexec_rlc_df= coin_history_df4
iexec_rlc_df

           fecha  price_iexec_rlc  market_iexec_rlc  vol_iexec_rlc
0     2018-01-02         2.161015      1.708732e+08   6.299613e+06
1     2018-01-03         1.982401      1.567500e+08   3.702223e+06
2     2018-01-04         2.531889      2.001984e+08   5.049802e+06
3     2018-01-05         2.617530      2.069702e+08   7.083848e+06
4     2018-01-06         2.597251      2.053667e+08   1.818261e+06
...          ...              ...               ...            ...
2048  2023-08-12         1.274145      9.226344e+07   7.923951e+06
2049  2023-08-13         1.265843      9.161938e+07   7.010957e+06
2050  2023-08-14         1.285919      9.298982e+07   6.880533e+06
2051  2023-08-15         1.282705      9.284710e+07   6.912548e+06
2052  2023-08-16         1.204342      8.726209e+07   6.836781e+06

[2053 rows x 4 columns]

insure

In [29]:
coin_history5 = cg.get_coin_market_chart_range_by_id(id='insure',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df5 = pd.DataFrame(coin_history5['prices'], columns=['Timestamp', 'Price'])
coin_history_df5['Timestamp'] = pd.to_datetime(coin_history_df5['Timestamp'], unit='ms')

coin_history_df5['date'] = coin_history_df5['Timestamp'].dt.date
coin_history_df5['market_caps'] = [entry[1] for entry in coin_history5['market_caps']]
coin_history_df5['total_volumes'] = [entry[1] for entry in coin_history5['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df5 = coin_history_df5[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df5.columns = ['fecha', 'price_insure', 'market_insure', 'vol_insure']
insure_df= coin_history_df5
insure_df

           fecha  price_insure  market_insure    vol_insure
0     2020-01-09      0.035876   0.000000e+00   3587.581786
1     2020-01-10      0.041817   0.000000e+00  14256.896836
2     2020-01-11      0.027383   0.000000e+00   6609.098579
3     2020-01-12      0.028457   0.000000e+00   6286.395737
4     2020-01-13      0.040329   0.000000e+00  20826.551356
...          ...           ...            ...           ...
1311  2023-08-12      0.003330   8.813258e+07  62627.090740
1312  2023-08-13      0.003332   8.827692e+07  84086.749194
1313  2023-08-14      0.003278   8.672178e+07   6899.774644
1314  2023-08-15      0.003282   8.687849e+07  90366.173163
1315  2023-08-16      0.003150   8.335709e+07   2177.563116

[1316 rows x 4 columns]

numeraire

In [34]:
coin_history6 = cg.get_coin_market_chart_range_by_id(id='numeraire',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df6 = pd.DataFrame(coin_history6['prices'], columns=['Timestamp', 'Price'])
coin_history_df6['Timestamp'] = pd.to_datetime(coin_history_df6['Timestamp'], unit='ms')

coin_history_df6['date'] = coin_history_df6['Timestamp'].dt.date
coin_history_df6['market_caps'] = [entry[1] for entry in coin_history6['market_caps']]
coin_history_df6['total_volumes'] = [entry[1] for entry in coin_history6['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df6 = coin_history_df6[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df6.columns = ['fecha', 'price_numeraire', 'market_numeraire', 'vol_numeraire']
numeraire_df= coin_history_df6
numeraire_df

           fecha  price_numeraire  market_numeraire  vol_numeraire
0     2018-01-02        38.732422      5.022011e+07   4.027714e+06
1     2018-01-03        39.374628      5.105279e+07   2.069248e+06
2     2018-01-04        38.482857      4.989653e+07   2.031430e+06
3     2018-01-05        34.212698      4.435988e+07   2.839278e+06
4     2018-01-06        34.460281      4.466625e+07   2.113814e+06
...          ...              ...               ...            ...
2048  2023-08-12        12.705028      7.994125e+07   3.495735e+06
2049  2023-08-13        12.794226      8.048884e+07   2.622239e+06
2050  2023-08-14        13.047064      8.204331e+07   2.709118e+06
2051  2023-08-15        13.450749      8.445572e+07   2.568850e+06
2052  2023-08-16        12.794064      8.044343e+07   3.629881e+06

[2053 rows x 4 columns]

ocean-protocol

In [35]:
coin_history7 = cg.get_coin_market_chart_range_by_id(id='ocean-protocol',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df7 = pd.DataFrame(coin_history7['prices'], columns=['Timestamp', 'Price'])
coin_history_df7['Timestamp'] = pd.to_datetime(coin_history_df7['Timestamp'], unit='ms')

coin_history_df7['date'] = coin_history_df7['Timestamp'].dt.date
coin_history_df7['market_caps'] = [entry[1] for entry in coin_history7['market_caps']]
coin_history_df7['total_volumes'] = [entry[1] for entry in coin_history7['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df7 = coin_history_df7[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df7.columns = ['fecha', 'price_ocean', 'market_ocean', 'vol_ocean']
ocean_protocol_df= coin_history_df7
ocean_protocol_df

           fecha  price_ocean  market_ocean     vol_ocean
0     2019-05-04     0.039082  0.000000e+00  9.424766e+05
1     2019-05-05     0.031010  0.000000e+00  7.347528e+05
2     2019-05-06     0.029629  0.000000e+00  4.260043e+05
3     2019-05-07     0.030764  0.000000e+00  4.835867e+05
4     2019-05-08     0.031758  0.000000e+00  4.723533e+05
...          ...          ...           ...           ...
1561  2023-08-12     0.345864  1.501700e+08  1.889695e+07
1562  2023-08-13     0.339593  1.473134e+08  1.266022e+07
1563  2023-08-14     0.339646  1.473155e+08  1.194134e+07
1564  2023-08-15     0.351257  1.524952e+08  2.464305e+07
1565  2023-08-16     0.326646  1.418038e+08  2.140582e+07

[1566 rows x 4 columns]

origintrail

In [36]:
from_date = '01-01-2018'
to_date = '16-08-2023'

from_timestamp = int(time.mktime(time.strptime(from_date, '%d-%m-%Y')))
to_timestamp = int(time.mktime(time.strptime(to_date, '%d-%m-%Y')))
coin_history8 = cg.get_coin_market_chart_range_by_id(id='origintrail',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df8 = pd.DataFrame(coin_history8['prices'], columns=['Timestamp', 'Price'])
coin_history_df8['Timestamp'] = pd.to_datetime(coin_history_df8['Timestamp'], unit='ms')

coin_history_df8['date'] = coin_history_df8['Timestamp'].dt.date
coin_history_df8['market_caps'] = [entry[1] for entry in coin_history8['market_caps']]
coin_history_df8['total_volumes'] = [entry[1] for entry in coin_history8['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df8 = coin_history_df8[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df8.columns = ['fecha', 'price_origintrail', 'market_origintrail', 'total_volumes_origintrail']
origintrail_df= coin_history_df8
origintrail_df

,fecha,price_origintrail,market_origintrail,total_volumes_origintrail
0,2018-02-02,0.319075,0.000000e+00,1.688170e+06
1,2018-02-03,0.274930,6.997178e+07,6.277100e+05
2,2018-02-04,0.305833,7.783682e+07,6.558760e+05
3,2018-02-05,0.256268,6.522216e+07,6.236880e+05
4,2018-02-06,0.179954,4.579966e+07,5.028170e+05
...,...,...,...,...
2017,2023-08-12,0.233306,8.933555e+07,1.027379e+06
2018,2023-08-13,0.236261,9.035114e+07,9.781690e+05
2019,2023-08-14,0.235641,9.016963e+07,7.460226e+05
2020,2023-08-15,0.236319,9.051774e+07,8.703785e+05
2021,2023-08-16,0.225315,8.619304e+07,1.133187e+06

render-token

In [37]:
coin_history9 = cg.get_coin_market_chart_range_by_id(id='render-token',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df9 = pd.DataFrame(coin_history9['prices'], columns=['Timestamp', 'Price'])
coin_history_df9['Timestamp'] = pd.to_datetime(coin_history_df9['Timestamp'], unit='ms')

coin_history_df9['date'] = coin_history_df9['Timestamp'].dt.date
coin_history_df9['market_caps'] = [entry[1] for entry in coin_history9['market_caps']]
coin_history_df9['total_volumes'] = [entry[1] for entry in coin_history9['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df9 = coin_history_df9[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df9.columns = ['fecha', 'price_render', 'market_render', 'vol_render']
render_token_df= coin_history_df9
render_token_df

           fecha  price_render  market_render    vol_render
0     2020-06-15      0.051188   0.000000e+00  2.201840e+04
1     2020-06-16      0.051188   0.000000e+00  2.201840e+04
2     2020-06-17      0.061080   0.000000e+00  2.990920e+04
3     2020-06-18      0.095549   0.000000e+00  7.478731e+04
4     2020-06-19      0.075271   0.000000e+00  3.655930e+04
...          ...           ...            ...           ...
1153  2023-08-12      1.677597   6.198509e+08  1.373117e+07
1154  2023-08-13      1.671681   6.185112e+08  7.985510e+06
1155  2023-08-14      1.653088   6.111054e+08  1.002222e+07
1156  2023-08-15      1.720606   6.360971e+08  2.357220e+07
1157  2023-08-16      1.626652   6.012803e+08  2.128357e+07

[1158 rows x 4 columns]

singularitynet

In [38]:
coin_history10 = cg.get_coin_market_chart_range_by_id(id='singularitynet',
                                                    vs_currency='usd',
                                                    from_timestamp=from_timestamp,
                                                    to_timestamp=to_timestamp,
                                                    localization=False)

# Se desanidan los datos debido a que los datos para todas las columnas (price,market_caps,total_volumes) vienen en formato [fechaunix,dato]

coin_history_df10 = pd.DataFrame(coin_history10['prices'], columns=['Timestamp', 'Price'])
coin_history_df10['Timestamp'] = pd.to_datetime(coin_history_df10['Timestamp'], unit='ms')

coin_history_df10['date'] = coin_history_df10['Timestamp'].dt.date
coin_history_df10['market_caps'] = [entry[1] for entry in coin_history10['market_caps']]
coin_history_df10['total_volumes'] = [entry[1] for entry in coin_history10['total_volumes']]

# Reordenar las columnas según lo deseado
coin_history_df10 = coin_history_df10[['date', 'Price', 'market_caps', 'total_volumes']]
coin_history_df10.columns = ['fecha', 'price_singularitynet', 'market_singularitynet', 'vol_singularitynet']
singularitynet_df= coin_history_df10
singularitynet_df

,fecha,price_singularitynet,market_singularitynet,vol_singularitynet
0,2018-01-22,0.892969,0.000000e+00,1.873402e+06
1,2018-01-23,0.772134,0.000000e+00,3.735368e+06
2,2018-01-24,0.724543,0.000000e+00,3.511334e+06
3,2018-01-25,0.729957,0.000000e+00,3.724039e+06
4,2018-01-26,0.814894,0.000000e+00,4.715006e+06
...,...,...,...,...
2027,2023-08-12,0.209684,2.575028e+08,2.036828e+07
2028,2023-08-13,0.206348,2.532286e+08,1.905248e+07
2029,2023-08-14,0.215221,2.642028e+08,2.835462e+07
2030,2023-08-15,0.219514,2.698449e+08,4.556091e+07
2031,2023-08-16,0.205947,2.528097e+08,3.316031e+07

A pesar de que se especificó la misma fecha para todos, las siguientes monedas empiezan en las siguientes fechas:

•	Akash: 2020-10-16

•	Singularitynet: 2018-01-22

•	render_token: 2020-06-15

•	origintrail_df: 2018-02-02	

•	ocean_df: 2019-05-04

•	numeraire_df: 2018-01-02

•	insure_df: 2020-01-09

•	iexec_rlc_df: 2018-01-02

•	fetch_ai_df: 2019-03-01

•	everipedia_df: 2018-07-17

Se exportan a csv

In [39]:
singularitynet_df.to_csv('singularitynet_df',index=False)
render_token_df.to_csv('render_token_df',index=False)
origintrail_df.to_csv('origintrail_df',index=False)
ocean_protocol_df.to_csv('ocean_df',index=False)
numeraire_df.to_csv('numeraire_df',index=False)
insure_df.to_csv('insure_df',index=False)
iexec_rlc_df.to_csv('iexec_rlc_df',index=False)
fetch_ai_df.to_csv('fetch_ai_df',index=False)
everipedia_df.to_csv('everipedia_df',index=False)
akash_network_df.to_csv('akash_df',index=False)

In [126]:
#Merge de df
union5=pd.merge(fetch_ai_df,everipedia_df, on='fecha', how='right')
union4=pd.merge(insure_df,iexec_rlc_df, on='fecha', how='right')
union2=pd.merge(render_token_df,origintrail_df, on='fecha', how='right')
union6=pd.merge(singularitynet_df,numeraire_df, on='fecha', how='right')
union1=pd.merge(ocean_df,akash_df, on='fecha', how='left')


union7=pd.merge(union4,union5,on='fecha',how='left')
union8=pd.merge(union2,union6,on='fecha',how='right')
union10=pd.merge(union7,union8,on='fecha', how='outer')

In [169]:
union10.to_csv('union10',index=False)

In [170]:
union=pd.read_csv('union10')
union

,fecha,price_insure,market_insure,vol_insure,price_iexec_rlc,market_iexec_rlc,vol_iexec_rlc,price_fetch_ai,market_fetch_ai,vol_fetch_ai,...,vol_render,price_origintrail,market_origintrail,total_volumes_origintrail,price_singularitynet,market_singularitynet,vol_singularitynet,price_numeraire,market_numeraire,vol_numeraire
0,2018-01-02,NaN,NaN,NaN,2.161015,1.708732e+08,6.299613e+06,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.732422,5.022011e+07,4.027714e+06
1,2018-01-03,NaN,NaN,NaN,1.982401,1.567500e+08,3.702223e+06,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.374628,5.105279e+07,2.069248e+06
2,2018-01-04,NaN,NaN,NaN,2.531889,2.001984e+08,5.049802e+06,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.482857,4.989653e+07,2.031430e+06
3,2018-01-05,NaN,NaN,NaN,2.617530,2.069702e+08,7.083848e+06,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.212698,4.435988e+07,2.839278e+06
4,2018-01-06,NaN,NaN,NaN,2.597251,2.053667e+08,1.818261e+06,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.460281,4.466625e+07,2.113814e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2048,2023-08-12,0.003330,8.813258e+07,62627.090740,1.274145,9.226344e+07,7.923951e+06,0.202119,2.108971e+08,1.137004e+07,...,1.373117e+07,0.233306,8.933555e+07,1.027379e+06,0.209684,2.575028e+08,2.036828e+07,12.705028,7.994125e+07,3.495735e+06
2049,2023-08-13,0.003332,8.827692e+07,84086.749194,1.265843,9.161938e+07,7.010957e+06,0.200333,2.090437e+08,1.132715e+07,...,7.985510e+06,0.236261,9.035114e+07,9.781690e+05,0.206348,2.532286e+08,1.905248e+07,12.794226,8.048884e+07,2.622239e+06
2050,2023-08-14,0.003278,8.672178e+07,6899.774644,1.285919,9.298982e+07,6.880533e+06,0.219619,2.291141e+08,4.594561e+07,...,1.002222e+07,0.235641,9.016963e+07,7.460226e+05,0.215221,2.642028e+08,2.835462e+07,13.047064,8.204331e+07,2.709118e+06
2051,2023-08-15,0.003282,8.687849e+07,90366.173163,1.282705,9.284710e+07,6.912548e+06,0.220334,2.300798e+08,1.052221e+08,...,2.357220e+07,0.236319,9.051774e+07,8.703785e+05,0.219514,2.698449e+08,4.556091e+07,13.450749,8.445572e+07,2.568850e+06
2052,2023-08-16,0.003150,8.335709e+07,2177.563116,1.204342,8.726209e+07,6.836781e+06,0.203116,2.118678e+08,3.675603e+07,...,2.128357e+07,0.225315,8.619304e+07,1.133187e+06,0.205947,2.528097e+08,3.316031e+07,12.794064,8.044343e+07,3.629881e+06

In [172]:
total_data_historica=pd.merge(union,union1,on='fecha',how='outer')

In [174]:
total_data_historica.columns

Index(['fecha', 'price_insure', 'market_insure', 'vol_insure',
       'price_iexec_rlc', 'market_iexec_rlc', 'vol_iexec_rlc',
       'price_fetch_ai', 'market_fetch_ai', 'vol_fetch_ai', 'price_everipedia',
       'market_everipedia', 'vol_everipedia', 'price_render', 'market_render',
       'vol_render', 'price_origintrail', 'market_origintrail',
       'total_volumes_origintrail', 'price_singularitynet',
       'market_singularitynet', 'vol_singularitynet', 'price_numeraire',
       'market_numeraire', 'vol_numeraire', 'price_ocean', 'market_ocean',
       'vol_ocean', 'price_akash-network', 'market_akash', 'vol_akash'],
      dtype='object')

In [175]:
total_data_historica.to_csv('total_data_historica',index=False)

Se definen los dataframes para la comparación HISTÓRICA de las 10 monedas por precio,market,volumen.

In [176]:
df_price=total_data_historica[['fecha','price_insure','price_iexec_rlc','price_fetch_ai','price_everipedia','price_singularitynet','price_akash-network','price_ocean','price_numeraire','price_render','price_origintrail']]
df_market=total_data_historica[['fecha','market_insure','market_iexec_rlc','market_fetch_ai','market_everipedia','market_singularitynet','market_akash','market_ocean','market_numeraire','market_render','market_origintrail']]
df_volumen=total_data_historica[['fecha','vol_insure','vol_iexec_rlc','vol_fetch_ai','vol_everipedia','vol_singularitynet','vol_akash','vol_ocean','vol_numeraire','vol_render','total_volumes_origintrail']]

In [177]:
#Se renombran columnas para df_volumen
df_volumen.rename(columns={'fecha':'Fecha','vol_insure': 'Insure', 'vol_iexec_rlc': 'Iexec_rlc',
'vol_fetch_ai':'Fetch_ai','vol_everipedia':'Everipedia','vol_singularitynet':'Singularitynet','vol_akash':'Akash',
'vol_ocean':'Ocean','vol_numeraire':'Numeraire','vol_render':'Render','total_volumes_origintrail':'Origintrail'}, inplace=True)

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_7404\2306167901.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_volumen.rename(columns={'fecha':'Fecha','vol_insure': 'Insure', 'vol_iexec_rlc': 'Iexec_rlc',

In [178]:
#Se renombran columnas para df_price
df_price.rename(columns={'fecha':'Fecha','price_insure': 'Insure', 'price_iexec_rlc': 'Iexec_rlc',
'price_fetch_ai':'Fetch_ai','price_everipedia':'Everipedia','price_singularitynet':'Singularitynet','price_akash-network':'Akash',
'price_ocean':'Ocean','price_numeraire':'Numeraire','price_render':'Render','price_origintrail':'Origintrail'}, inplace=True)

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_7404\1081598639.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_price.rename(columns={'fecha':'Fecha','price_insure': 'Insure', 'price_iexec_rlc': 'Iexec_rlc',

In [179]:
#Se renombran columnas para df_market
df_market.rename(columns={'fecha':'Fecha','market_insure': 'Insure', 'market_iexec_rlc': 'Iexec_rlc',
'market_fetch_ai':'Fetch_ai','market_everipedia':'Everipedia','market_singularitynet':'Singularitynet','market_akash':'Akash',
'market_ocean':'Ocean','market_numeraire':'Numeraire','market_render':'Render','market_origintrail':'Origintrail'}, inplace=True)

C:\Users\Jocelyn\AppData\Local\Temp\ipykernel_7404\622873661.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_market.rename(columns={'fecha':'Fecha','market_insure': 'Insure', 'market_iexec_rlc': 'Iexec_rlc',

In [180]:
df_price.to_csv('df_price',index=False)
df_market.to_csv('df_market',index=False)
df_volumen.to_csv('df_volumen',index=False)

# Extracción de datos Actuales con la librería CoinGeckoApi

In [1]:
from pycoingecko import CoinGeckoAPI
import pandas as pd

cg = CoinGeckoAPI()

monedas_lista = ['akash-network', 'everipedia', 'fetch-ai', 'iexec-rlc', 'insure','numeraire', 'ocean-protocol', 'origintrail', 'render-token','singularitynet']

# Se obtienen los datos de mercado para las monedas específicas
coin_markets = cg.get_coins_markets(vs_currency='usd', ids=monedas_lista)

# Datos de mercado
coin_markets_df = pd.DataFrame(coin_markets)
coin_markets_df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,render-token,rndr,Render,https://assets.coingecko.com/coins/images/1163...,1.460000,543903475,69,776604953,25730892,1.480000,...,5.310243e+08,5.310243e+08,8.780000,-83.35035,2021-11-21T10:03:19.097Z,0.036657,3889.28546,2020-06-16T13:22:25.900Z,None,2023-08-24T01:58:05.454Z
1,akash-network,akt,Akash Network,https://assets.coingecko.com/coins/images/1278...,1.480000,323528301,104,578401085,5310592,1.550000,...,2.173287e+08,3.885390e+08,8.070000,-81.54458,2021-04-06T18:59:48.484Z,0.164994,803.22684,2022-11-21T20:30:53.727Z,None,2023-08-24T01:58:03.656Z
2,singularitynet,agix,SingularityNET,https://assets.coingecko.com/coins/images/2138...,0.180732,221960170,143,360183362,29090752,0.181768,...,1.324917e+09,2.000000e+09,0.950230,-81.05441,2018-01-28T00:00:00.000Z,0.007472,2309.48314,2020-03-13T02:24:16.528Z,"{'times': 0.807323087764063, 'currency': 'usd'...",2023-08-24T01:58:10.472Z
3,fetch-ai,fet,Fetch.ai,https://assets.coingecko.com/coins/images/5681...,0.207269,216365873,145,239078313,28218315,0.209295,...,1.152998e+09,1.152998e+09,1.170000,-82.29718,2021-09-08T02:24:24.858Z,0.008170,2439.61606,2020-03-13T02:24:18.347Z,"{'times': 1.3906495260483391, 'currency': 'usd...",2023-08-24T01:58:05.599Z
4,ocean-protocol,ocean,Ocean Protocol,https://assets.coingecko.com/coins/images/3687...,0.309076,133970637,202,435223314,15027394,0.309344,...,1.410000e+09,1.410000e+09,1.930000,-84.04421,2021-04-10T09:24:58.915Z,0.012848,2296.74706,2019-08-11T00:00:00.000Z,"{'times': 1.5756314240942366, 'currency': 'usd...",2023-08-24T01:58:04.463Z
5,origintrail,trac,OriginTrail,https://assets.coingecko.com/coins/images/1877...,0.223521,85515767,258,111698149,866770,0.224277,...,5.000000e+08,5.000000e+08,3.500000,-93.61635,2021-11-03T18:09:57.627Z,0.003853,5707.55783,2020-03-13T02:24:12.031Z,"{'times': 1.235205926692715, 'currency': 'usd'...",2023-08-24T01:58:03.274Z
6,iexec-rlc,rlc,iExec RLC,https://assets.coingecko.com/coins/images/646/...,1.043000,75482676,288,90725966,7114235,1.061000,...,8.699978e+07,8.699978e+07,15.510000,-93.27136,2021-05-10T17:59:51.557Z,0.153815,578.51646,2018-12-15T00:00:00.000Z,None,2023-08-24T01:58:02.872Z
7,numeraire,nmr,Numeraire,https://assets.coingecko.com/coins/images/752/...,11.390000,71776712,296,125742763,2045320,11.470000,...,1.084589e+07,1.100000e+07,93.150000,-87.75750,2021-05-16T10:29:06.362Z,2.060000,452.45458,2018-11-27T00:00:00.000Z,None,2023-08-24T01:58:11.356Z
8,everipedia,iq,IQ,https://assets.coingecko.com/coins/images/5010...,0.004363,71440695,297,91506876,244035,0.004474,...,1.639499e+10,2.100000e+10,0.072382,-93.97683,2018-07-16T07:35:38.970Z,0.000630,591.49419,2020-03-13T02:29:15.457Z,None,2023-08-24T01:58:09.849Z
9,insure,sure,inSure DeFi,https://assets.coingecko.com/coins/images/1035...,0.002652,70011955,304,232810696,197012,0.002839,...,8.800000e+10,8.800000e+10,0.113970,-97.66957,2021-01-06T21:22:32.766Z,0.000156,1601.89616,2021-06-28T04:52:56.935Z,None,2023-08-24T01:57:57.028Z

In [2]:
coin_markets_df.to_csv('coin_markets_df',index=False)